#!/bin/sh -eu

export TEMPLATE=template.tpl
: ${DOCROOT:=$PWD}

case "${1:-}" in
	index)
		test -e "$DOCROOT/.autoindex" || {
			echo "Create empty .autoindex file in $DOCROOT" >&2
			echo "to confirm you want to create index.md automatically" >&2
			exit 2
		}
		INDEX=index.md
		INDEX_TEMPLATE="${INDEX%.md}.head"
		test -s "$INDEX_TEMPLATE" && \
			cat "$INDEX_TEMPLATE" > "$INDEX" || \
			cat <<-"EOF" > "$INDEX"
			% Table of contents
			%
			%

			# Contents

			EOF
		find -L "$DOCROOT" -name \*.md ! -name "$INDEX" -type f -print0 | \
			xargs -r0 -n1 \
			awk -v DR="$DOCROOT" 'NR==1{
				sub("% ","",$0)
				sub(DR,"",FILENAME)
				sub(".md$",".html",FILENAME)
				printf "- [%s](%s)\n",$0,FILENAME
			}' >> "$INDEX"
		;;
	clean)
		exec find -L "$DOCROOT" -name \*.html -type f -print -delete
		;;
	all)
		find -L "$DOCROOT" -name \*.md -type f -print0 | \
			xargs -r0 -n1 -P10 $0
		;;
	*.md)
		INFILE="$1"
		OUTFILE="${INFILE%md}html"
		test -s "${INFILE%md}tpl" && TEMPLATE="${INFILE%md}tpl"
		# exit if output is already up to date
		test -f "$OUTFILE" && \
			test "$INFILE" -ot "$OUTFILE" && \
			test "$TEMPLATE" -ot "$OUTFILE" && exit 0
		printf '%s\t=>\t%s\n' "$INFILE" "$OUTFILE"
		exec theme -C -toc -E -t "$TEMPLATE" -o "$OUTFILE" "$INFILE"
		;;
	*)
		cat <<-EOF >&2
		Usage:
		${0##*/} ACTION | filename.md

		Actions supported:

		- all: process all .md files (but not index)
		- index: create index file (list appended to index.head)
		- clean: remove ALL .html files (be careful!)

		DOCROOT environment variable is looked for files, otherwise,
		PWD is used
		EOF
		exit 1
		;;
esac
